Update the integration testing readme
compound-finance/gateway pull request #333
Opened 2021-05-20 16:27 UTC by waynenilsen

2021-05-20 16:39 UTC, jflatow commented
Cool, thanks for trying to keep this up to date

2021-06-08 06:38 UTC, hayesgm requested changes
Awesome thanks; one thing in regards to the new default being `release` instead of debug. Also, possibly just focus on using the `yarn XYZ` variants since they can be kept up-to-date a little easier.

2021-06-08 06:38 UTC, hayesgm commented on integration/README.md
> +You can run the tests with Gateway compiled in release or debug profile. The default profile is **debug**.
This is not true, at least not anymore. Really now we should use `yarn build` and `yarn test` which will do all of the right things all the time.

2021-06-08 06:38 UTC, hayesgm commented on integration/README.md
> +gateway> WASM_BUILD_RUSTFLAGS='--cfg feature=\"integration\"' cargo build --release --features integration
I feel like these will be fragile versus using `yarn build` from `integration/`

2021-06-08 06:38 UTC, hayesgm commented on integration/README.md
> +If you did NOT build with the `--release` flag, then run the test using:
You can actually just do `PROFILE=debug yarn test ...` I believe.

2021-06-08 22:35 UTC, merged